title: "Questia"
author: "Matthew Kaminski"
description: "An open source game and game engine"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

navigation:
  - index.html
  - about.md
  - archive.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  github: "https://github.com/SquireGames/Questia"

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
